name: build

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Containerfile'
      - '**.repo'
      - 'entrypoint.sh'
      - 'upgrade-firmware.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          image: hpe-toolkit
          tags: ${{ github.sha }} latest
        id: image

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.image.outputs.image }}
          tags: ${{ steps.image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
